CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id UUID NOT NULL,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_public_id UNIQUE (public_id),
    CONSTRAINT uq_app_user_normalized_email UNIQUE (normalized_email),
    CONSTRAINT ck_app_user_email_trimmed
        CHECK (email <> '' AND email = BTRIM(email)),
    CONSTRAINT ck_app_user_normalized_email
        CHECK (
            normalized_email <> ''
            AND normalized_email = BTRIM(normalized_email)
            AND normalized_email = LOWER(normalized_email)
        ),
    CONSTRAINT ck_app_user_password_hash_not_blank
        CHECK (password_hash <> '' AND password_hash = BTRIM(password_hash)),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    CONSTRAINT ck_app_user_audit_order
        CHECK (updated_at >= created_at),
    CONSTRAINT ck_app_user_version
        CHECK (version >= 0)
);

CREATE TABLE role (
    id SMALLINT NOT NULL,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT uq_role_name UNIQUE (name),
    CONSTRAINT ck_role_id_positive CHECK (id > 0),
    CONSTRAINT ck_role_name CHECK (name IN ('USER', 'ADMIN'))
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id SMALLINT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE RESTRICT
);

CREATE INDEX ix_user_role_role_id ON user_role (role_id);

INSERT INTO role (id, name)
VALUES
    (1, 'USER'),
    (2, 'ADMIN');
